### ISSUE TITLE
FWIW DHT 11, or 22 sensors

### ISSUE THREAD

**Issue by Grey-Lancaster** [BOlaerts/ESP32-2432s028#10]
You can just use the provided 4 pin connector with a DHT sensor and still have a GPIO left over

```
sensor:
  # - platform: dallas
  #   address: xxxxxxxxxxx
  #   name: "CYD Temp" 
  - platform: dht
    pin: GPIO22
    model: AUTO_DETECT
    temperature:
      name: "CYD Temperature"    
    humidity:
      name: "CYD Humidity"
    update_interval: 60s  
```
