### ISSUE TITLE
Example code not working - display seems rotated

### ISSUE THREAD

**Issue by andreas-bulling** [BOlaerts/ESP32-2432s028#5]
Hi,

I've tried to use your sample code but the display seems rotated - any idea for how to fix this?

**Comment by casebeer** [comment]
I had the same issue – display rotated 90°, vertical wrapping, and junk displayed on the right hand side. 

Changing the display model to `ILI9342` (vs. `ILI9341`) fixed it for me. Presumably I have a board version with a different display. 

```
display:
  - platform: ili9xxx
    model: ILI9342
    ...
```

**Comment by Failbike** [comment]
Thanks @casebeer that fixed the overlapping/junk issue.  But it was still in landscape and the buttons didn't work.
I added `rotation: 90`.
```
display:
  - platform: ili9xxx
    model: ILI9342
    rotation: 90
    ...
```
And then swapped the `name: Music` and `name: Power` button locations to match the images.
```
binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status

  - platform: touchscreen
    name: Music
    x_min: 30
    x_max: 90
    y_min: 20
    y_max: 80

  - platform: touchscreen
    name: Power
    x_min: 150
    x_max: 210
    y_min: 20
    y_max: 80
```
