### ISSUE TITLE
display seems to draw in the wrong direction

### ISSUE THREAD

**Issue by binagun** [BOlaerts/ESP32-2432s028#7]
Hi i just tried the code example but it seems to draw the image in the wrong orientation, leaving a band of noise on the right hand of the display ( assuming the usb-c port is left ). i assume that it might be an easy fix some where however i'm not wel versed with display drawing code and lcd libs
![20231022_113336](https://github.com/BOlaerts/ESP32-2432s028/assets/1360835/dfd7847f-fe2d-4a0d-94d1-aeeb16cc82d5)

**Comment by leifnel** [comment]
There are different display types.
I use 
```
display:
  - platform: ili9xxx
    model: ILI9342
    rotation: 90
    spi_id: lcd
    cs_pin: 15
    dc_pin: 2
```

I haven't managed to fix the touch yet.
